config/routes.rb
Rails.application.routes.draw do
  resources :plans
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plan.rb
class Plan < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: %i[ show edit update destroy ]

  # GET /plans or /plans.json
  def index
    @plans = Plan.all
  end

  # GET /plans/1 or /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans or /plans.json
  def create
    @plan = Plan.new(plan_params)

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: "Plan was successfully created." }
        format.json { render :show, status: :created, location: @plan }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1 or /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: "Plan was successfully updated." }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1 or /plans/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url, notice: "Plan was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def plan_params
      params.require(:plan).permit(:title1, :title2, :title3, :persona, :online, :description1, :description2, :description3, :regio, :sectorcat, :functieact, :diploma, :language, :color1, :color2, :color3, :string, :color4, :color5, :keywords1, :keywords2, :keywords3, :keywords4, :keywords5, :text1, :text2, :text3, :text4, :text5, :text6, :text7, :text8, :text9, :text10, :text11, :text12, :text13, :text14, :text15, :text16, :text17, :text18, :text19, :text20, :description1, :description2, :description3, :description4, :description5, :description6, :description7, :description8, :description9, :description10, :description11, :description12, :description13, :description14, :description15, :description16, :description17, :description18, :description19, :description20, :integer1, :integer2, :integer3, :integer4, :integer5, :integer6, :integer7, :integer8, :integer9, :integer10, :boolean1, :boolean2, :boolean3, :boolean4, :boolean5)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <title>Tap</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script>

  </head>

  <body>
    <div class="min-h-screen bg-gray-100">
      <div class="bg-indigo-600 pb-32">
        <nav class="bg-indigo-600 border-b border-indigo-300 border-opacity-25 lg:border-none">
          <div class="max-w-7xl mx-auto px-2 sm:px-4 lg:px-8">
            <div class="relative h-16 flex items-center justify-between lg:border-b lg:border-indigo-400 lg:border-opacity-25">
              <div class="px-2 flex items-center lg:px-0">
                <div class="flex-shrink-0">
                  <img class="block h-8 w-8" src="https://tailwindui.com/img/logos/workflow-mark-indigo-300.svg" alt="Workflow">
                </div>
                <div class="hidden lg:block lg:ml-10">
                  <div class="flex space-x-4">
                    <!-- Current: "bg-indigo-700 text-white", Default: "text-white hover:bg-indigo-500 hover:bg-opacity-75" -->
                    <a href="#" class="bg-indigo-700 text-white rounded-md py-2 px-3 text-sm font-medium" aria-current="page">
                      Dashboard
                    </a>
    
                    <a href="#" class="text-white hover:bg-indigo-500 hover:bg-opacity-75 rounded-md py-2 px-3 text-sm font-medium">
                      Team
                    </a>
    
                    <a href="#" class="text-white hover:bg-indigo-500 hover:bg-opacity-75 rounded-md py-2 px-3 text-sm font-medium">
                      Projects
                    </a>
    
                    <a href="#" class="text-white hover:bg-indigo-500 hover:bg-opacity-75 rounded-md py-2 px-3 text-sm font-medium">
                      Calendar
                    </a>
    
                    <a href="#" class="text-white hover:bg-indigo-500 hover:bg-opacity-75 rounded-md py-2 px-3 text-sm font-medium">
                      Reports
                    </a>
                  </div>
                </div>
              </div>
              <div class="flex-1 px-2 flex justify-center lg:ml-6 lg:justify-end">
                <div class="max-w-lg w-full lg:max-w-xs">
                  <label for="search" class="sr-only">Search</label>
                  <div class="relative text-gray-400 focus-within:text-gray-600">
                    <div class="pointer-events-none absolute inset-y-0 left-0 pl-3 flex items-center">
                      <!-- Heroicon name: solid/search -->
                      <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                        <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd" />
                      </svg>
                    </div>
                    <input id="search" class="block w-full bg-white py-2 pl-10 pr-3 border border-transparent rounded-md leading-5 text-gray-900 placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-indigo-600 focus:ring-white focus:border-white sm:text-sm" placeholder="Search" type="search" name="search">
                  </div>
                </div>
              </div>
              <div class="flex lg:hidden">
                <!-- Mobile menu button -->
                <button type="button" class="bg-indigo-600 p-2 rounded-md inline-flex items-center justify-center text-indigo-200 hover:text-white hover:bg-indigo-500 hover:bg-opacity-75 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-indigo-600 focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
                  <span class="sr-only">Open main menu</span>
                  <!--
                    Heroicon name: outline/menu
    
                    Menu open: "hidden", Menu closed: "block"
                  -->
                  <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                  </svg>
                  <!--
                    Heroicon name: outline/x
    
                    Menu open: "block", Menu closed: "hidden"
                  -->
                  <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              </div>
              <div class="hidden lg:block lg:ml-4">
                <div class="flex items-center">
                  <button type="button" class="bg-indigo-600 flex-shrink-0 rounded-full p-1 text-indigo-200 hover:text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-indigo-600 focus:ring-white">
                    <span class="sr-only">View notifications</span>
                    <!-- Heroicon name: outline/bell -->
                    <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
                    </svg>
                  </button>
    
                  <!-- Profile dropdown -->
                  <div class="ml-3 relative flex-shrink-0" x-data="{ open: false }">
                    <div>
                      <button type="button" @click="open = ! open" class="bg-indigo-600 rounded-full flex text-sm text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-indigo-600 focus:ring-white" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
                        <span class="sr-only">Open user menu</span>
                        <img class="rounded-full h-8 w-8" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
                      </button>
                    </div>
    
                    <!--
                      Dropdown menu, show/hide based on menu state.
    
                      Entering: "transition ease-out duration-100"
                        From: "transform opacity-0 scale-95"
                        To: "transform opacity-100 scale-100"
                      Leaving: "transition ease-in duration-75"
                        From: "transform opacity-100 scale-100"
                        To: "transform opacity-0 scale-95"
                    -->
                    <div x-show="open" class="origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg py-1 bg-white ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1">
                      <!-- Active: "bg-gray-100", Not Active: "" -->
                      <a href="#" class="block py-2 px-4 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-0">
                        Your Profile
                      </a>
    
                      <a href="#" class="block py-2 px-4 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-1">
                        Settings
                      </a>
    
                      <a href="#" class="block py-2 px-4 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-2">
                        Sign out
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
    
          <!-- Mobile menu, show/hide based on menu state. -->
          <div class="lg:hidden" id="mobile-menu">
            <div class="px-2 pt-2 pb-3 space-y-1">
              <!-- Current: "bg-indigo-700 text-white", Default: "text-white hover:bg-indigo-500 hover:bg-opacity-75" -->
              <a href="#" class="bg-indigo-700 text-white block rounded-md py-2 px-3 text-base font-medium" aria-current="page">
                Dashboard
              </a>
    
              <a href="#" class="text-white hover:bg-indigo-500 hover:bg-opacity-75 block rounded-md py-2 px-3 text-base font-medium">
                Team
              </a>
    
              <a href="#" class="text-white hover:bg-indigo-500 hover:bg-opacity-75 block rounded-md py-2 px-3 text-base font-medium">
                Projects
              </a>
    
              <a href="#" class="text-white hover:bg-indigo-500 hover:bg-opacity-75 block rounded-md py-2 px-3 text-base font-medium">
                Calendar
              </a>
    
              <a href="#" class="text-white hover:bg-indigo-500 hover:bg-opacity-75 block rounded-md py-2 px-3 text-base font-medium">
                Reports
              </a>
            </div>
            <div class="pt-4 pb-3 border-t border-indigo-700">
              <div class="px-5 flex items-center">
                <div class="flex-shrink-0">
                  <img class="rounded-full h-10 w-10" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
                </div>
                <div class="ml-3">
                  <div class="text-base font-medium text-white">Tom Cook</div>
                  <div class="text-sm font-medium text-indigo-300">tom@example.com</div>
                </div>
                <button type="button" class="ml-auto bg-indigo-600 flex-shrink-0 rounded-full p-1 text-indigo-200 hover:text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-indigo-600 focus:ring-white">
                  <span class="sr-only">View notifications</span>
                  <!-- Heroicon name: outline/bell -->
                  <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
                  </svg>
                </button>
              </div>
              <div class="mt-3 px-2 space-y-1">
                <a href="#" class="block rounded-md py-2 px-3 text-base font-medium text-white hover:bg-indigo-500 hover:bg-opacity-75">
                  Your Profile
                </a>
    
                <a href="#" class="block rounded-md py-2 px-3 text-base font-medium text-white hover:bg-indigo-500 hover:bg-opacity-75">
                  Settings
                </a>
    
                <a href="#" class="block rounded-md py-2 px-3 text-base font-medium text-white hover:bg-indigo-500 hover:bg-opacity-75">
                  Sign out
                </a>
              </div>
            </div>
          </div>
        </nav>
        <header class="py-10">
          <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <h1 class="text-3xl font-bold text-white" id="animateMe">
              Talent Acquisition Plans <%= Date.today.strftime("%A") %>
            </h1>
          </div>
        </header>
      </div>
    
      <main class="-mt-32">
        <div class="max-w-7xl mx-auto pb-12 px-4 sm:px-6 lg:px-8">
          <!-- Replace with your content -->
          <%= yield %>
          <!-- /End replace -->
        </div>
      </main>
    </div>
    <script>
              $(document).ready(function() {
            $('.dropdown').click(function() {
              $(this).closest(".group").find(".dropdown-menu").toggle();
            });
        });
    </script>
  </body>
</html> 

app/views/plans/_form.html.erb
<%= form_with(model: plan) do |form| %>
  <% if plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
        <% plan.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title1 %>
    <%= form.text_field :title1 %>
  </div>

  <div class="field">
    <%= form.label :title2 %>
    <%= form.text_field :title2 %>
  </div>

  <div class="field">
    <%= form.label :title3 %>
    <%= form.text_field :title3 %>
  </div>

  <div class="field">
    <%= form.label :persona %>
    <%= form.text_field :persona %>
  </div>

  <div class="field">
    <%= form.label :online %>
    <%= form.check_box :online %>
  </div>

  <div class="field">
    <%= form.label :description1 %>
    <%= form.text_area :description1 %>
  </div>

  <div class="field">
    <%= form.label :description2 %>
    <%= form.text_area :description2 %>
  </div>

  <div class="field">
    <%= form.label :description3 %>
    <%= form.text_area :description3 %>
  </div>

  <div class="field">
    <%= form.label :regio %>
    <%= form.text_field :regio %>
  </div>

  <div class="field">
    <%= form.label :sectorcat %>
    <%= form.text_field :sectorcat %>
  </div>

  <div class="field">
    <%= form.label :functieact %>
    <%= form.text_field :functieact %>
  </div>

  <div class="field">
    <%= form.label :diploma %>
    <%= form.text_field :diploma %>
  </div>

  <div class="field">
    <%= form.label :language %>
    <%= form.text_area :language %>
  </div>

  <div class="field">
    <%= form.label :color1 %>
    <%= form.text_field :color1 %>
  </div>

  <div class="field">
    <%= form.label :color2 %>
    <%= form.text_field :color2 %>
  </div>

  <div class="field">
    <%= form.label :color3 %>
    <%= form.text_field :color3 %>
  </div>

  <div class="field">
    <%= form.label :string %>
    <%= form.text_field :string %>
  </div>

  <div class="field">
    <%= form.label :color4 %>
    <%= form.text_field :color4 %>
  </div>

  <div class="field">
    <%= form.label :color5 %>
    <%= form.text_field :color5 %>
  </div>

  <div class="field">
    <%= form.label :keywords1 %>
    <%= form.text_area :keywords1 %>
  </div>

  <div class="field">
    <%= form.label :keywords2 %>
    <%= form.text_area :keywords2 %>
  </div>

  <div class="field">
    <%= form.label :keywords3 %>
    <%= form.text_area :keywords3 %>
  </div>

  <div class="field">
    <%= form.label :keywords4 %>
    <%= form.text_area :keywords4 %>
  </div>

  <div class="field">
    <%= form.label :keywords5 %>
    <%= form.text_area :keywords5 %>
  </div>

  <div class="field">
    <%= form.label :text1 %>
    <%= form.text_field :text1 %>
  </div>

  <div class="field">
    <%= form.label :text2 %>
    <%= form.text_field :text2 %>
  </div>

  <div class="field">
    <%= form.label :text3 %>
    <%= form.text_field :text3 %>
  </div>

  <div class="field">
    <%= form.label :text4 %>
    <%= form.text_field :text4 %>
  </div>

  <div class="field">
    <%= form.label :text5 %>
    <%= form.text_field :text5 %>
  </div>

  <div class="field">
    <%= form.label :text6 %>
    <%= form.text_field :text6 %>
  </div>

  <div class="field">
    <%= form.label :text7 %>
    <%= form.text_field :text7 %>
  </div>

  <div class="field">
    <%= form.label :text8 %>
    <%= form.text_field :text8 %>
  </div>

  <div class="field">
    <%= form.label :text9 %>
    <%= form.text_field :text9 %>
  </div>

  <div class="field">
    <%= form.label :text10 %>
    <%= form.text_field :text10 %>
  </div>

  <div class="field">
    <%= form.label :text11 %>
    <%= form.text_field :text11 %>
  </div>

  <div class="field">
    <%= form.label :text12 %>
    <%= form.text_field :text12 %>
  </div>

  <div class="field">
    <%= form.label :text13 %>
    <%= form.text_field :text13 %>
  </div>

  <div class="field">
    <%= form.label :text14 %>
    <%= form.text_field :text14 %>
  </div>

  <div class="field">
    <%= form.label :text15 %>
    <%= form.text_field :text15 %>
  </div>

  <div class="field">
    <%= form.label :text16 %>
    <%= form.text_field :text16 %>
  </div>

  <div class="field">
    <%= form.label :text17 %>
    <%= form.text_field :text17 %>
  </div>

  <div class="field">
    <%= form.label :text18 %>
    <%= form.text_field :text18 %>
  </div>

  <div class="field">
    <%= form.label :text19 %>
    <%= form.text_field :text19 %>
  </div>

  <div class="field">
    <%= form.label :text20 %>
    <%= form.text_field :text20 %>
  </div>

  <div class="field">
    <%= form.label :description1 %>
    <%= form.text_area :description1 %>
  </div>

  <div class="field">
    <%= form.label :description2 %>
    <%= form.text_area :description2 %>
  </div>

  <div class="field">
    <%= form.label :description3 %>
    <%= form.text_area :description3 %>
  </div>

  <div class="field">
    <%= form.label :description4 %>
    <%= form.text_area :description4 %>
  </div>

  <div class="field">
    <%= form.label :description5 %>
    <%= form.text_area :description5 %>
  </div>

  <div class="field">
    <%= form.label :description6 %>
    <%= form.text_area :description6 %>
  </div>

  <div class="field">
    <%= form.label :description7 %>
    <%= form.text_area :description7 %>
  </div>

  <div class="field">
    <%= form.label :description8 %>
    <%= form.text_area :description8 %>
  </div>

  <div class="field">
    <%= form.label :description9 %>
    <%= form.text_area :description9 %>
  </div>

  <div class="field">
    <%= form.label :description10 %>
    <%= form.text_area :description10 %>
  </div>

  <div class="field">
    <%= form.label :description11 %>
    <%= form.text_area :description11 %>
  </div>

  <div class="field">
    <%= form.label :description12 %>
    <%= form.text_area :description12 %>
  </div>

  <div class="field">
    <%= form.label :description13 %>
    <%= form.text_area :description13 %>
  </div>

  <div class="field">
    <%= form.label :description14 %>
    <%= form.text_area :description14 %>
  </div>

  <div class="field">
    <%= form.label :description15 %>
    <%= form.text_area :description15 %>
  </div>

  <div class="field">
    <%= form.label :description16 %>
    <%= form.text_area :description16 %>
  </div>

  <div class="field">
    <%= form.label :description17 %>
    <%= form.text_area :description17 %>
  </div>

  <div class="field">
    <%= form.label :description18 %>
    <%= form.text_area :description18 %>
  </div>

  <div class="field">
    <%= form.label :description19 %>
    <%= form.text_area :description19 %>
  </div>

  <div class="field">
    <%= form.label :description20 %>
    <%= form.text_area :description20 %>
  </div>

  <div class="field">
    <%= form.label :integer1 %>
    <%= form.number_field :integer1 %>
  </div>

  <div class="field">
    <%= form.label :integer2 %>
    <%= form.number_field :integer2 %>
  </div>

  <div class="field">
    <%= form.label :integer3 %>
    <%= form.number_field :integer3 %>
  </div>

  <div class="field">
    <%= form.label :integer4 %>
    <%= form.number_field :integer4 %>
  </div>

  <div class="field">
    <%= form.label :integer5 %>
    <%= form.number_field :integer5 %>
  </div>

  <div class="field">
    <%= form.label :integer6 %>
    <%= form.number_field :integer6 %>
  </div>

  <div class="field">
    <%= form.label :integer7 %>
    <%= form.number_field :integer7 %>
  </div>

  <div class="field">
    <%= form.label :integer8 %>
    <%= form.number_field :integer8 %>
  </div>

  <div class="field">
    <%= form.label :integer9 %>
    <%= form.number_field :integer9 %>
  </div>

  <div class="field">
    <%= form.label :integer10 %>
    <%= form.number_field :integer10 %>
  </div>

  <div class="field">
    <%= form.label :boolean1 %>
    <%= form.check_box :boolean1 %>
  </div>

  <div class="field">
    <%= form.label :boolean2 %>
    <%= form.check_box :boolean2 %>
  </div>

  <div class="field">
    <%= form.label :boolean3 %>
    <%= form.check_box :boolean3 %>
  </div>

  <div class="field">
    <%= form.label :boolean4 %>
    <%= form.check_box :boolean4 %>
  </div>

  <div class="field">
    <%= form.label :boolean5 %>
    <%= form.check_box :boolean5 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/plans/edit.html.erb
<h1>Editing Plan</h1>

<%= render 'form', plan: @plan %>

<%= link_to 'Show', @plan %> |
<%= link_to 'Back', plans_path %>

app/views/plans/index.html.erb
<ul role="list" class="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
  <% @plans.reverse_each do |plan| %>
  <li class="col-span-1 flex flex-col text-center bg-white rounded-lg shadow divide-y divide-gray-200">
    <div class="flex-1 flex flex-col p-8">
      <img class="w-32 h-32 flex-shrink-0 mx-auto rounded-full" src="https://source.unsplash.com/256x256/?<%= plan.text1 %>" alt="">
      <h3 class="mt-6 text-gray-900 text-sm font-medium">Logisticien</h3>
      <dl class="mt-1 flex-grow flex flex-col justify-between">
        <dt class="sr-only">Title</dt>
        <dd class="text-gray-500 text-sm">Paradigm Representative</dd>
        <dt class="sr-only">Role</dt>
        <dd class="mt-3">
          <span class="px-2 py-1 text-green-800 text-xs font-medium bg-green-100 rounded-full">Bruxelles</span>
        </dd>
      </dl>
    </div>
    <div>
      <div class="-mt-px flex divide-x divide-gray-200">
        <div class="w-0 flex-1 flex">
          <%= link_to 'Show', plan, class:"text-white relative -mr-px w-0 flex-1 inline-flex items-center justify-center py-4 text-sm font-medium border border-transparent rounded-bl-lg bg-indigo-800" %>
        </div>
      </div>
    </div>
  </li> 
  <% end %>
</ul>

app/views/plans/new.html.erb
<h1>New Plan</h1>

<%= render 'form', plan: @plan %>

<%= link_to 'Back', plans_path %>